### ISSUE TITLE
Cleanup and Validate CSS

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#10]
Once some of the UI stabilizes we'll need to cleanup the CSS.  I'm not sure how much of bootstrap we're actually using on the CSS side vs. rolling our own.

**Comment by carlsonp** [comment]
Make sure it's valid as well: https://jigsaw.w3.org/css-validator/

**Comment by lpberg** [comment]
before releasing 1.0

**Comment by carlsonp** [comment]
Looks like Atom or a plugin has some lint checking on CSS as well, I can tackle those.

**Comment by carlsonp** [comment]
Manually run and checked.
