### ISSUE TITLE
Enhancement: Add support for Net Promoter Score (NPS)

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#116]

**Comment by tyler-stone** [comment]
Hey, mind if I grab this one? Doesn't look like it would be too hard - very similar to the SUS implementation

**Comment by lpberg** [comment]
@tyler-stone For sure. That would be great. Let us know if you have questions. Submit a merge request when you are ready.

**Comment by carlsonp** [comment]
:+1:
