### ISSUE TITLE
No way to clear responses for single URL setup

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#160]
Reproduce: create a SUS and use the single URL, add some responses, go to edit page and there is no way to clear responses without clicking on unique links and then clearing them

**Comment by lpberg** [comment]
Good point. There is a difference between participant links and responses on the front end - but we do not represent that on the backend. Not sure how to fix this best yet.

**Comment by lpberg** [comment]
@carlsonp This is probably worth a discussion of how/where we want to list links (incomplete responses) vs completed responses.

**Comment by lpberg** [comment]
Todo for this item:
1) Have links (incomplete responses) only on edit page
2) Have completed responses only on results page
3) Ensure delete all works for links
4) Ensure single delete works for results page (completed responses)
5) Include "Response Summary" on all results pages (only showing completed responses)
