### ISSUE TITLE
Logo hover color 

### ISSUE THREAD

**Issue by jfwyatt** [carlsonp/kort#170]
When user hovers over Kort logo from landing page, the text turns white & is barely visible. 

![image](https://user-images.githubusercontent.com/26099660/33444466-640ca09e-d5c8-11e7-849f-50922d6525aa.png)
![image](https://user-images.githubusercontent.com/26099660/33444478-6bb60aec-d5c8-11e7-80ad-19e66a1265eb.png)

**Comment by lpberg** [comment]
@jfwyatt Good find!
