### ISSUE TITLE
node warning - unhandled promise from 'connect-mongo'

### ISSUE THREAD

**Issue by lpberg** [carlsonp/kort#178]
(node:59542) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: cb is not a function

Not yet sure how to reproduce it.

**Comment by carlsonp** [comment]
https://github.com/jdesboeufs/connect-mongo/issues/272

**Comment by carlsonp** [comment]
Appears to be fixed upstream.  Reopen this if it surfaces again.
