### ISSUE TITLE
Bootbox seems to be validating the email and password forms

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#196]
Bootbox is checking these and preventing the subsequent call.  This means our flash messages are not being displayed.  Add client-side checking to display messages about missing email or password fields on both the admin users modal as well as the new registration modal on the login page.  Don't start work on this until #126 is finished.

**Comment by lpberg** [comment]
@carlsonp Not sure I understand this one. Lets chat.

**Comment by lpberg** [comment]
I'm wondering if it just makes more sense to have a user registration page. A lot of sites do it, and it might be cleaner/easier development wise.

**Comment by lpberg** [comment]
It is possible to add client-side validation in bootbox. 

- [ ] Reset Password (from admin)

- [ ] New User Registration (from index)

- [ ] Add New User (from admin)
