### ISSUE TITLE
Explain study types on main admin page

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#21]
Right now there isn't much on the admin page.  It would be nice to explain the types of studies that are available and the types of results that can be obtained by each.  Links to wikipedia, etc.

**Comment by lpberg** [comment]
This was something on the index page - may bring it back. Needs more thought. Good Point.

**Comment by carlsonp** [comment]
Started in e58c2d911fff3a6fce3228807fa4c1d8e98d8851

**Comment by lpberg** [comment]
ended in 9c3195fa8ea2a97f50e134c1f26b959ea7beb2e1
