### ISSUE TITLE
Group names not saved when submitting response to Card Sort research

### ISSUE THREAD

**Issue by artfabrique** [carlsonp/kort#231]
We ran into a situation when respondent creates a number of groups with automated names then he puts the cards in that groups and then renames each group.
The group names which a sent to the server are still "Group 1" ... "Group N"

**Comment by carlsonp** [comment]
@artfabrique Are you able to try this branch and fix?  We believe this addresses the issue.  https://github.com/carlsonp/kort/pull/233

**Comment by carlsonp** [comment]
Think this has fixed it, if not let us know.  Thanks.
