### ISSUE TITLE
Automatic group naming leads to corrupt results

### ISSUE THREAD

**Issue by artfabrique** [carlsonp/kort#238]
Heatmap groups answer by group-names in open Card Sorting. This gives invalid results because users forget to give a name to the groups and in that case, all "Group 1" - "Group N" will be grouped between completely different respondents.

The solution is to give auto-names to the groups with some random noun at the end. For example "Group 1 Koala" ... "Group N Koala"

**Comment by carlsonp** [comment]
@lpberg Can you look into requiring a group name upon creation?
