### ISSUE TITLE
Scrub templates for incorrect template tags

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#31]
See `tags` here: http://ejs.co/

I don't think we want to be using unescaped values.

<% 'Scriptlet' tag, for control-flow, no output
<%= Outputs the value into the template (HTML escaped)
<%- Outputs the unescaped value into the template
<%# Comment tag, no execution, no output
<%% Outputs a literal '<%'
%> Plain ending tag
-%> Trim-mode ('newline slurp') tag, trims following newline
```
<%-
```

**Comment by lpberg** [comment]
Yes we do - only for the includes. Or else it strips the HTML out (which is what is in the includes). I learned this the hard way.
