### ISSUE TITLE
make a github page for kort

### ISSUE THREAD

**Issue by lpberg** [carlsonp/kort#67]

**Comment by lpberg** [comment]
You may need to do this one. Not sure I can permission wise.

**Comment by carlsonp** [comment]
https://carlsonp.github.io/kort/

Use "docs" folder.  Apparently they don't provide kort.github.io.

https://help.github.com/articles/about-supported-custom-domains/

**Comment by lpberg** [comment]
development started - how should i use things like bootstrap css? cdn? local?
