### ISSUE TITLE
build task/node matrix for tree test results

### ISSUE THREAD

**Issue by lpberg** [carlsonp/kort#69]
the results are in task order
the number is the nodeID and the text is the node name.

**Comment by carlsonp** [comment]
We should probably talk about this one because we need to make sure the data is in the right format for export analysis as well as to display on the page (heatmap, dendrogram, etc.).

Plotlyjs cannot do dendrograms.  d3.js can:

https://bl.ocks.org/mbostock/4063570

**Comment by lpberg** [comment]
yeah, i remember talking about just doing a heat table. also, the results aren't posting in a format we need yet.

**Comment by lpberg** [comment]
Correction: The results are in the correct format. However, DataTables is combining the arrays into a single list. (display only)

**Comment by carlsonp** [comment]
Decided to go different direction
