### ISSUE TITLE
Product reaction cards submit button

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#75]
The styling of the product reaction cards button should be different and brighter than the word selections.  In addition, we should duplicate the button and also put it at the top of the page in case people don't scroll.

**Comment by carlsonp** [comment]
Use the same style for the final submission button on the 5 word selection as well.

**Comment by lpberg** [comment]
I changed style differently. Lets see what usability testing comes back with. Two buttons could be annoying.
