### ISSUE TITLE
Scrollbars are showing up

### ISSUE THREAD

**Issue by carlsonp** [carlsonp/kort#8]
Presumably the padding is adding some additional pixels and making vertical and horizontal scroll bars show up in the browser window.

**Comment by lpberg** [comment]
for which view?

**Comment by carlsonp** [comment]
Cardsort

**Comment by lpberg** [comment]
Is this still a thing?

**Comment by lpberg** [comment]
Is this still happening? I think I fixed this.

**Comment by lpberg** [comment]
closing as I can't reproduce it
