### ISSUE TITLE
Usability Test Round 1

### ISSUE THREAD

**Issue by lpberg** [carlsonp/kort#83]
Run the application by a UX person who hasn't see it yet. Make it task based.

**Comment by lpberg** [comment]
1 Participant tested. - recommendations have been added to issues.

**Comment by jfwyatt** [comment]
do you have your test script? I can potentially run with some other experts as participants.

**Comment by lpberg** [comment]
@jfwyatt I do not. It was fairly informal. I tried to sick to basic tasks around creating / editing studies, and managing responses (creating, finding links, etc). If you decide to use one, even basic, feel free to share so I or others can use it. Thanks!

**Comment by lpberg** [comment]
Completed lite testing.
